# Generated by Django 3.1.7 on 2021-07-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_company', '0002_certificate_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='CEO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ФИО', models.CharField(max_length=100)),
                ('позиция', models.CharField(max_length=200)),
                ('данные_в_виде_списка', models.TextField()),
                ('данные', models.TextField()),
                ('изображение', models.ImageField(upload_to='ceo')),
            ],
        ),
    ]
