# Generated by Django 3.1.7 on 2021-07-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_company', '0003_ceo'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='выделенный_текст',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
