# Generated by Django 3.1.7 on 2021-07-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_company', '0004_history_выделенный_текст'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='выделенный_текст',
            field=models.TextField(),
        ),
    ]
