# Generated by Django 3.1.7 on 2021-07-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_company', '0005_auto_20210713_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='выделенный_текст',
            field=models.TextField(null=True),
        ),
    ]
