# Generated by Django 3.1.7 on 2021-07-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='выделенный_текст_на_главной_странице',
            field=models.CharField(default='.', max_length=200),
            preserve_default=False,
        ),
    ]
