# Generated by Django 3.1.7 on 2021-07-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0002_block_выделенный_текст_на_главной_странице'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='выделенный_текст_на_главной_странице',
            field=models.TextField(null=True),
        ),
    ]
