# Generated by Django 3.1.7 on 2021-07-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0003_auto_20210713_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='выделенный_текст_на_главной_странице',
            field=models.TextField(blank=True, null=True),
        ),
    ]
