# Generated by Django 3.1.7 on 2021-07-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0004_auto_20210713_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='выделяющийся_текст',
            field=models.TextField(blank=True, null=True),
        ),
    ]
