# Generated by Django 3.1.7 on 2021-07-10 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('изображение', models.ImageField(upload_to='products')),
                ('объем', models.CharField(max_length=50)),
                ('название', models.CharField(max_length=100)),
                ('тип', models.CharField(max_length=100)),
                ('описание', models.TextField()),
            ],
        ),
    ]
