# Generated by Django 3.1.7 on 2021-07-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('название', models.CharField(max_length=100)),
                ('описание', models.TextField()),
                ('изображение', models.ImageField(upload_to='mainCompanyBlock')),
                ('название2', models.CharField(max_length=100)),
                ('описание2', models.TextField()),
                ('изображение2', models.ImageField(upload_to='mainCompanyBlock')),
            ],
        ),
        migrations.CreateModel(
            name='Clue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('домен1', models.CharField(max_length=30)),
                ('текст1', models.CharField(max_length=50)),
                ('домен2', models.CharField(max_length=30)),
                ('текст2', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('год1', models.CharField(max_length=15)),
                ('название1', models.CharField(max_length=80)),
                ('описание1', models.TextField()),
                ('год2', models.CharField(max_length=15)),
                ('название2', models.CharField(max_length=80)),
                ('описание2', models.TextField()),
                ('год3', models.CharField(max_length=15)),
                ('название3', models.CharField(max_length=80)),
                ('описание3', models.TextField()),
                ('год4', models.CharField(max_length=15)),
                ('название4', models.CharField(max_length=110)),
                ('описание4', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('название', models.CharField(max_length=100)),
                ('описание', models.TextField()),
                ('текст1', models.CharField(max_length=50)),
                ('подтекст1', models.CharField(max_length=30)),
                ('текст2', models.CharField(max_length=50)),
                ('подтекст2', models.CharField(max_length=30)),
                ('изображение', models.ImageField(upload_to='main')),
            ],
        ),
    ]
