# Generated by Django 3.1.7 on 2021-07-11 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0003_auto_20210710_0217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyhistory',
            old_name='год1',
            new_name='год',
        ),
        migrations.RenameField(
            model_name='companyhistory',
            old_name='название1',
            new_name='название',
        ),
        migrations.RenameField(
            model_name='companyhistory',
            old_name='описание1',
            new_name='описание',
        ),
        migrations.RemoveField(
            model_name='companyhistory',
            name='год2',
        ),
        migrations.RemoveField(
            model_name='companyhistory',
            name='год3',
        ),
        migrations.RemoveField(
            model_name='companyhistory',
            name='год4',
        ),
        migrations.RemoveField(
            model_name='companyhistory',
            name='название2',
        ),
        migrations.RemoveField(
            model_name='companyhistory',
            name='название3',
        ),
        migrations.RemoveField(
            model_name='companyhistory',
            name='название4',
        ),
        migrations.RemoveField(
            model_name='companyhistory',
            name='описание2',
        ),
        migrations.RemoveField(
            model_name='companyhistory',
            name='описание3',
        ),
        migrations.RemoveField(
            model_name='companyhistory',
            name='описание4',
        ),
    ]
