# Generated by Django 3.1.7 on 2021-07-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0004_auto_20210711_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyhistory',
            name='название',
            field=models.CharField(max_length=200),
        ),
    ]
