# Generated by Django 3.1.7 on 2021-07-11 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0005_auto_20210711_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutcompany',
            name='изображение2',
        ),
        migrations.RemoveField(
            model_name='aboutcompany',
            name='название2',
        ),
        migrations.RemoveField(
            model_name='aboutcompany',
            name='описание2',
        ),
    ]
