# Generated by Django 3.1.7 on 2021-07-12 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0006_auto_20210711_2339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clue',
            old_name='домен1',
            new_name='домен',
        ),
        migrations.RenameField(
            model_name='clue',
            old_name='текст1',
            new_name='текст',
        ),
        migrations.RemoveField(
            model_name='clue',
            name='домен2',
        ),
        migrations.RemoveField(
            model_name='clue',
            name='текст2',
        ),
    ]
