# Generated by Django 3.1.7 on 2021-07-12 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0007_auto_20210712_0009'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyHistory',
        ),
    ]
