# Generated by Django 3.1.7 on 2021-07-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0008_delete_companyhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcompany',
            name='выделенный_текст',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='main',
            name='выделенный_текст',
            field=models.CharField(default='.', max_length=200),
            preserve_default=False,
        ),
    ]
