# Generated by Django 3.1.7 on 2021-07-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0010_auto_20210713_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutcompany',
            name='выделенный_текст',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='выделенный_текст',
            field=models.TextField(blank=True, null=True),
        ),
    ]
